export const PRODUCT_CATEGORIES = {
  Electronics: ["Audio", "Video", "Wearables", "Cameras", "Home Entertainment"],
  Accessories: ["Chargers", "Cables", "Bags", "Screen Protectors", "Mounts"],
  Laptops: ["Gaming Laptops", "Ultrabooks", "Business Laptops", "2-in-1", "Student Laptops"],
  Tablets: ["Android Tablets", "iPads", "Windows Tablets", "Kids Tablets"],
  "Smart Phones": ["Android Phones", "iPhones", "5G Phones", "Refurbished Phones"],
  Headphones: ["In-Ear", "Over-Ear", "Wireless", "Noise-Canceling", "Gaming Headsets"],
  Desktops: ["Gaming Desktops", "All-in-One", "Mini PCs", "Workstations"],
  "Gaming Accessories": ["Controllers", "VR Headsets", "Gaming Mice", "Keyboards", "Gaming Chairs"],
  Clothing: ["Men", "Women", "Kids", "Activewear", "Footwear", "Accessories"],
  Utilities: ["Home Appliances", "Kitchen Gadgets", "Cleaning Tools", "Storage Solutions"],
  Hardware: ["Tools", "Fasteners", "Electrical", "Plumbing", "Gardening"],
  "Agro Sales": ["Seeds", "Seedlings", "Fertilizers", "Pesticides", "Farm Tools", "Animal Feed"],
  Grocery: ["Condiments", "Snacks", "Beverages", "Staples", "Household Essentials"],
  "School Supplies": ["Notebooks", "Pens & Pencils", "Markers & Highlighters", "Binders & Folders", "Backpacks", "Calculators", "Art Supplies"],
  "Home & Living": ["Furniture", "Decor", "Kitchenware", "Storage", "Bedding"],
  Tactical: ["Gear", "Protective Wear", "Camping", "Outdoor", "Accessories"],
  Fashion: ["Men", "Women", "Kids", "Footwear", "Accessories"],
  Sports: ["Cricket", "Basketball", "Football", "Tennis"],
  "Property or Real Estate": ["Residential", "Commercial", "Land", "Rental", "Vacation"],
};
